### ISSUE TITLE
Fix Japanese Translations

### ISSUE THREAD

**Issue by FraserTooth** [FraserTooth/japan_grid_carbon_api_website#4]
The Japanese translations are terrible and they need fixed.

- Translations to be updated in `jp.json` [Link](https://github.com/FraserTooth/japan_grid_carbon_api_website/blob/master/src/translations/jp.json)
- Please use the english translations as a guide
- Strike a more relatable than professional tone, and use simple language, as this website is aimed at educating normal people as well as energy professionals.

- (Feel free to adjust the english translation if you feel it could be better worded)
- Please discuss and ask your questions below 👇

**Comment by darensin01** [comment]
Hi @FraserTooth 

Am thinking of modifying the JP translations of たぶん to the following:

- はい、データはライブではないのせいで、高い精度で当てることができません。

- このAPIは有史データを電力会社のウェブサイトからダウンロードをしています。このデータによって、予報しています。

- ライブ電気市場と発電データが提供されていないから、予報するしかないです。

- APIの開発につれて、予報の精度が高くなったらいいと思います。それより、電力会社が必要なライブデータを提供したら、予報が正確になるかもしれません。

What do you think?

**Comment by FraserTooth** [comment]
Hey @darensin01, unfortunately, my Japanese isn't good enough to determine whether this sounds natural or not 😬 
Thank you for your effort, but I think it would be best for a native speaker to tackle this issue. 🙇

**Comment by togami2864** [comment]
Hello! I'm native speaker of japanese and interested in translation of this repo.
Can I start contributing to it tomorrow?(because i'm busy today)

**Comment by FraserTooth** [comment]
@togami2864 sure!
Let me know if you have any questions about the terminology.

**Comment by togami2864** [comment]
@FraserTooth I have question.
I interpreted that 

Carbon Intensity [gC02/kWh]= (Carbon Intensity factor for that fuel type) * (proportion of energy generation that came from each fuel type)

Is my interpretation correct?

**Comment by FraserTooth** [comment]
@togami2864 yes I think you've understood correctly, but just to be fully clear heres a fuller example:

Carbon Intensity for period [gC02/kWh] = (Carbon Intensity Factor for Coal * Proportion of Coal Generation in Period)  + (Carbon Intensity Factor for Gas * Proportion of Gas Generation in Period)  + etc. etc. for all fuel types

**Comment by togami2864** [comment]
I've translated into jp.
Please review it! #10

**Comment by FraserTooth** [comment]
Great job, thanks a bunch!
