### ISSUE TITLE
The values of carbon intensity of coal and IGCC have been swapped in jp.json.

### ISSUE THREAD

**Issue by takuroumi** [FraserTooth/japan_grid_carbon_api_website#56]
In https://denkicarbon.jp/ , the explanation of the values of carbon intensity of coal and IGCC have been swapped.

![image](https://user-images.githubusercontent.com/24859675/154793249-a7be9427-f3bf-4a16-a1bd-b533241b439f.png)

I guess the following line in jp.json should be fixed to `"例えば、石炭の炭素強度係数は937 gCO₂/kWh、複合サイクルガスタービン（CCGT）は394 gCO₂/kWhです。"`
https://github.com/FraserTooth/japan_grid_carbon_api_website/blob/b8ee8b800fca2028579ba18c7ccb5d0069155270/src/translations/jp.json#L72

Also I confirmed the explanation in en.json is correct.
https://github.com/FraserTooth/japan_grid_carbon_api_website/blob/b8ee8b800fca2028579ba18c7ccb5d0069155270/src/translations/en.json#L72

**Comment by FraserTooth** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/25011388/154822609-c8c9bd32-6c9d-4a98-8380-cef3470fadf1.png">
Fixed and in production
